### ISSUE TITLE
Todo - features

### ISSUE THREAD

**Issue by MichelDiz** [MichelDiz/Dgraph-Digger-CLI#1]
- [ ] Add a 'Check' Cluster state command. See https://docs.dgraph.io/deploy/#more-about-dgraph-zero
- [ ] Add a 'Export' JSON to Live command.
- [ ] Add a 'Export database' Dgraph command. see https://docs.dgraph.io/deploy/#export-database
- [ ] Add a 'import CSV' to Live command.
- [ ] Add a 'import JSON' with auto blank-node feature to specific args to Live command. See https://github.com/dgraph-io/dgraph/issues/2848
- [ ] Add a 'Admin Operations' create 'Admin' command.
- [ ] Add a 'Shutdown Database' to Admin command.
- [ ] Add a 'allocate' UIDs to Admin command. See https://docs.dgraph.io/deploy/#more-about-dgraph-zero
- [ ] Add feature to continue a previous load. https://github.com/dgraph-io/dgraph/issues/3279
- [ ] Add a 'removeNode' to Admin command. 

- [ ] Add a 'Export' JSON to Live command.
